version: '3.9'

services:
  postgres:
    image: postgres:14-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  db_data: {}